import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Header from "@/ui/Header";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

export const metadata = {
  title: "TVPro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={redHatDisplay.variable}>
        <Header/>
        <div style={{ paddingTop: 80 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
